version: "3.9"

services:
  localstack:
    container_name: localstack
    image: localstack/localstack:2.3.2
    environment:
      - SERVICES=s3,cloudformation,sns
      - EDGE_PORT=4566
    ports:
      - "4566:4566"
    volumes:
      - localstack:/var/lib/localstack

volumes:
  localstack:
